apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: backstage-github-app
  namespace: backstage
  labels:
    app.kubernetes.io/part-of: backstage
    app.kubernetes.io/managed-by: flux
spec:
  itemPath: "vaults/${OP_VAULT}/items/${OP_ITEM_BACKSTAGE_GITHUB_APP}"
