---
# 1Password Helm chart registry
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword
  namespace: flux-system
spec:
  interval: 24h
  url: https://1password.github.io/connect-helm-charts
---
# MetalLB Helm chart registry
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 24h
  url: https://metallb.github.io/metallb
---
# Kyverno Helm chart registry (used by platform layer)
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 24h
  url: https://kyverno.github.io/kyverno
---
# democratic-csi Helm chart registry (TrueNAS CSI driver)
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  interval: 24h
  url: https://democratic-csi.github.io/charts/
---
# Grafana Helm chart registry (Alloy, Grafana, Loki, etc.)
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
