apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-nfs
  namespace: democratic-csi
spec:
  values:
    driver:
      config:
        zfs:
          datasetParentName: kaz.cloud/kozmox/k8/nfs/vols
          detachedSnapshotsDatasetParentName: kaz.cloud/kozmox/k8/nfs/snaps
