apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-wide.yaml
  - traefik-system.yaml
  - flux-system.yaml
  - backstage.yaml
  - monitoring.yaml
  - democratic-csi.yaml
  - arc-runners.yaml
  - arc-system.yaml
  - packer-runners.yaml
  - onepassword-system.yaml
  - kyverno-system.yaml
  - crossplane-system.yaml
  - reloader.yaml
  - policy-reporter.yaml
