apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-cloud-credentials
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: grafana-alloy
    app.kubernetes.io/managed-by: flux
spec:
  itemPath: "vaults/${OP_VAULT}/items/${OP_ITEM_GRAFANA_CLOUD}"
