{%- if values.enableSecret %}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ${{ values.opItemName }}
  namespace: ${{ values.namespace }}
  labels:
    app.kubernetes.io/part-of: ${{ values.name }}
    app.kubernetes.io/managed-by: flux
spec:
  itemPath: "vaults/{% raw %}${OP_VAULT}{% endraw %}/items/{% raw %}${OP_ITEM_{% endraw %}${{ values.name | upper | replace("-", "_") }}{% raw %}}{% endraw %}"
{%- endif %}
