apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-api-token
  namespace: external-dns
  labels:
    app.kubernetes.io/part-of: external-dns
    app.kubernetes.io/managed-by: flux
spec:
  itemPath: "vaults/${OP_VAULT}/items/${OP_ITEM_CLOUDFLARE}"
