apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pod-security-baseline.yaml
  - pod-security-restricted.yaml
  - require-resource-limits.yaml
  - require-standard-labels.yaml
  - supply-chain-policies.yaml
