---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-standard-labels
  labels:
    app.kubernetes.io/managed-by: flux
  annotations:
    policies.kyverno.io/title: Require Standard Labels
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: low
spec:
  background: true
  rules:
    - name: require-managed-by
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
                - DaemonSet
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno-system
      validate:
        failureAction: Audit
        message: "Resources must have 'app.kubernetes.io/managed-by' label."
        pattern:
          metadata:
            labels:
              app.kubernetes.io/managed-by: "?*"
