apiVersion: v1
kind: Namespace
metadata:
  name: reloader
  labels:
    app.kubernetes.io/managed-by: flux
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
      interval: 1h
  install:
    timeout: 10m
  upgrade:
    timeout: 10m
  values:
    reloader:
      watchGlobally: true
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
      podAnnotations:
        app.kubernetes.io/managed-by: flux
